
name: CI - Pull Request

# Triggers the workflow on pull request events
on: 
  pull_request:
  
jobs:
  
  build-and-test:
    
    runs-on: ubuntu-22.04
    container:
      image: python:3.12-slim
    strategy:
      matrix: 
        python-version: ["3.12"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}  
          uses: actions/setup-python@v4  
          with:  
            python-version: ${{ matrix.python-version }} 
        - name: Install poetry
          run: pip install poetry
        - name: Test with pytest  
          run: |  
            coverage run -m pytest  -v -s


